chore: fix S3 links in PR comments

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -1,10 +1,11 @@
 name: Pull Request
 on: [pull_request]
-env:
-  # NOTE: BUCKET_NAME gets displayed publicly!
+  # NOTE: BUCKET_NAME and REGION get displayed publicly!
   # But GitHub will not allow a secret to be used in job output
-  # so using env var to make link to PR test app.
+  # so using env vars to make link to PR test app.
+env:
   BUCKET_NAME: oit-test-bucket
+  REGION: eu-north-1
 jobs:
   build:
     name: Build
@@ -59,7 +60,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws-region: ${{ env.REGION }}
       # aws cli is avaiabled already in GH image
       # see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
       #      https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
@@ -69,12 +70,12 @@ jobs:
         if: ${{ always() }}
         id: result
         # NOTE: cannot use secrets.AWS_BUCKET for bucket, it'll make GitHub to skip output!
-        run: 'test -f deploy-ok && echo "::set-output name=result::- **✔️ Deployment**: Success 🚀 Test it here: <https://${{ env.BUCKET_NAME }}.s3.eu-north-1.amazonaws.com/prs/${{ github.event.number }}/${{ github.run_attempt }}/index.html>" || echo "::set-output name=result::- **🛑 Deployment**: FAILED 💔"'
+        run: 'test -f deploy-ok && echo "::set-output name=result::- **✔️ Deployment**: Success 🚀 Test it here: <https://oit-test-bucket.s3.${{ env.REGION }}.amazonaws.com/prs/${{ github.event.number }}/${{ github.run_attempt }}/index.html>" || echo "::set-output name=result::- **🛑 Deployment**: FAILED 💔"'
       - name: Set test link
         if: ${{ always() }}
         id: test-link
         # NOTE: cannot use secrets.AWS_BUCKET for bucket, it'll make GitHub to skip output!
-        run: echo "::set-output name=test-link::https://${{ env.BUCKET_NAME }}.s3.eu-north-1.amazonaws.com/prs/${{ github.event.number }}/${{ github.run_attempt }}/index.html"
+        run: echo "::set-output name=test-link::https://oit-test-bucket.s3.${{ env.REGION }}.amazonaws.com/prs/${{ github.event.number }}/${{ github.run_attempt }}/index.html"
 
   commitlint:
     name: Run commitlint
@@ -144,8 +145,7 @@ jobs:
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: `Great success! 🥳 Your pull request was built and has been deployed for testing:
-              <{{ needs.deploy.outputs.test-link }}>
+              body: `Great success! 🥳 Your pull request was built and has been deployed for testing: <${{ needs.deploy.outputs.test-link }}>
 
               **Job summary:**
 
