chore(ci): run eslint & translations check in same job
Should speed up checks a bit.

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -44,7 +44,7 @@ jobs:
       - name: Set result
         if: ${{ always() }}
         id: result
-        run: 'test -f build-ok && echo "::set-output name=result::- **✔️ Build**: Success 🛠️" || echo "::set-output name=result::- **🛑 Build**: FAILED 💩"'
+        run: 'test -f build-ok && echo "::set-output name=result::- **✔️ build**: Success 🛠️" || echo "::set-output name=result::- **🛑 build**: FAILED 💩"'
 
   deploy:
     name: Deploy
@@ -80,7 +80,7 @@ jobs:
         env:
           PR_NUM: ${{ github.event.number }}
         # NOTE: using secrets in output make GitHub to skip output!
-        run: 'test -f deploy-ok && echo "::set-output name=result::- **✔️ Deployment**: Success 🚀 Test it here: <${APP_SERVER}/pr/${PR_NUM}/${GITHUB_RUN_NUMBER}/index.html>" || echo "::set-output name=result::- **🛑 Deployment**: FAILED 💔"'
+        run: 'test -f deploy-ok && echo "::set-output name=result::- **✔️ deploy**: Success 🚀 Test it here: <${APP_SERVER}/pr/${PR_NUM}/${GITHUB_RUN_NUMBER}/index.html>" || echo "::set-output name=result::- **🛑 deploy**: FAILED 💔"'
       - name: Set test link
         if: ${{ always() }}
         id: test-link
@@ -130,15 +130,17 @@ jobs:
            echo "::set-output name=warn-many-commits::%0A**⚠️ WARNING: You have ${N} commits in your PR. GitHub API and/or wagoid/commitlint-github-action seems to be limited to 30 commits / PR, so commitlint check starts failing after that count! ⚠️**%0A"; \
           else echo "::set-output name=warn-many-commits::"; fi
 
-  eslint:
-    name: Run eslint
+  src-lints:
+    name: Run eslint and translations check
     # Run after build just in case to avoid cache getting messed up, but run always.
     # (Not sure if setup-node could handle parallel access).
     if: ${{ always() }}
     needs: [build]
     runs-on: ubuntu-latest
     outputs:
-      result: ${{ steps.result.outputs.result }}
+      es-result: ${{ steps.es-result.outputs.result }}
+      tr-result: ${{ steps.tr-result.outputs.result }}
+      tr-details: ${{ steps.tr-result.outputs.details }}
     steps:
       - name: Checkout
         uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3
@@ -155,42 +157,18 @@ jobs:
         run: pnpm install --frozen-lockfile
       - name: Run eslint
         run: pnpm run lint && touch eslint-ok
-      - name: Set result
-        if: ${{ always() }}
-        id: result
-        run: 'test -f eslint-ok && echo "::set-output name=result::- **✔️ eslint**: Success 👍" || echo "::set-output name=result::- **🛑 eslint**: FAILED 🧐"'
-
-  translation-check:
-    name: Check translations
-    # Run after eslint just in case to avoid cache getting messed up, but run always.
-    # (Not sure if setup-node could handle parallel access).
-    if: ${{ always() }}
-    needs: [eslint]
-    runs-on: ubuntu-latest
-    outputs:
-      result: ${{ steps.result.outputs.result }}
-      details: ${{ steps.result.outputs.details }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3
-      - name: Install pnpm
-        uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # renovate: tag=v2.2.2
-        with:
-          version: latest
-      - name: Setup Node.js
-        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # renovate: tag=v3
-        with:
-          node-version: lts/*
-          cache: 'pnpm' # cache example form: https://pnpm.io/continuous-integration#github-actions
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
       - name: Run translation check
+        if: ${{ always() }}
         run: |
           pnpm run build:tools
           node dist.local/tools/lang-check.js -m dist.local/tr-out.md && touch tr-ok
-      - name: Set result
+      - name: Set eslint result
         if: ${{ always() }}
-        id: result
+        id: es-result
+        run: 'test -f eslint-ok && echo "::set-output name=result::- **✔️ eslint**: Success 👍" || echo "::set-output name=result::- **🛑 eslint**: FAILED 🧐"'
+      - name: Set translations check result
+        if: ${{ always() }}
+        id: tr-result
         # NOTE: Multiline strings get "truncated" to only the first line. Newlines must be escaped as %0A.
         # See: https://github.community/t/set-output-truncates-multiline-strings/16852/3
         run: |
@@ -201,7 +179,7 @@ jobs:
 
   comment-success:
     name: Leave a comment on success
-    needs: [build, deploy, commitlint, eslint, translation-check]
+    needs: [build, deploy, commitlint, src-lints]
     runs-on: ubuntu-latest
     steps:
       - name: Leave a comment
@@ -223,10 +201,10 @@ jobs:
             ${{ needs.build.outputs.result }}
             ${{ needs.deploy.outputs.result }}
             ${{ needs.commitlint.outputs.result }}
-            ${{ needs.eslint.outputs.result }}
-            ${{ needs.translation-check.outputs.result }}
+            ${{ needs.src-lints.outputs.es-result }}
+            ${{ needs.src-lints.outputs.tr-result }}
 
-            ${{ needs.translation-check.outputs.details }}
+            ${{ needs.src-lints.outputs.tr-details }}
 
             Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
             })
@@ -234,7 +212,7 @@ jobs:
   comment-failure:
     name: Leave a comment on failure
     if: ${{ failure() }}
-    needs: [build, deploy, commitlint, eslint, translation-check]
+    needs: [build, deploy, commitlint, src-lints]
     runs-on: ubuntu-latest
     steps:
       - name: Leave a comment
@@ -256,10 +234,10 @@ jobs:
             ${{ needs.build.outputs.result }}
             ${{ needs.deploy.outputs.result }}
             ${{ needs.commitlint.outputs.result }}
-            ${{ needs.eslint.outputs.result }}
-            ${{ needs.translation-check.outputs.result }}
+            ${{ needs.src-lints.outputs.es-result }}
+            ${{ needs.src-lints.outputs.tr-result }}
 
-            ${{ needs.translation-check.outputs.details }}
+            ${{ needs.src-lints.outputs.tr-details }}
 
             Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
             })
