chore(ci): run translation check on pull requests

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -160,9 +160,48 @@ jobs:
         id: result
         run: 'test -f eslint-ok && echo "::set-output name=result::- **✔️ eslint**: Success 👍" || echo "::set-output name=result::- **🛑 eslint**: FAILED 🧐"'
 
+  translation-check:
+    name: Check translations
+    # Run after eslint just in case to avoid cache getting messed up, but run always.
+    # (Not sure if setup-node could handle parallel access).
+    if: ${{ always() }}
+    needs: [eslint]
+    runs-on: ubuntu-latest
+    outputs:
+      result: ${{ steps.result.outputs.result }}
+      details: ${{ steps.result.outputs.details }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3
+      - name: Install pnpm
+        uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # renovate: tag=v2.2.2
+        with:
+          version: latest
+      - name: Setup Node.js
+        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # renovate: tag=v3
+        with:
+          node-version: lts/*
+          cache: 'pnpm' # cache example form: https://pnpm.io/continuous-integration#github-actions
+      - name: Install dependencies
+        run: pnpm install --frozen-lockfile
+      - name: Run translation check
+        run: |
+          pnpm run build:tools
+          node dist.local/tools/lang-check.js -m dist.local/tr-out.md && touch tr-ok
+      - name: Set result
+        if: ${{ always() }}
+        id: result
+        # NOTE: Multiline strings get "truncated" to only the first line. Newlines must be escaped as %0A.
+        # See: https://github.community/t/set-output-truncates-multiline-strings/16852/3
+        run: |
+          test -f tr-ok && echo "::set-output name=result::- **✔️ translations check**: Success 👍" || echo "::set-output name=result::- **🛑 translations check**: FAILED 🧐 (see \"Translation check problems below\")"
+          output=$(cat dist.local/tr-out.md)
+          output="${output//$'\n'/'%0A'}"
+          test -f tr-ok && echo "::set-output name=details::" || echo "::set-output name=details::${output}"
+
   comment-success:
     name: Leave a comment on success
-    needs: [build, deploy, commitlint, eslint]
+    needs: [build, deploy, commitlint, eslint, translation-check]
     runs-on: ubuntu-latest
     steps:
       - name: Leave a comment
@@ -185,6 +224,9 @@ jobs:
             ${{ needs.deploy.outputs.result }}
             ${{ needs.commitlint.outputs.result }}
             ${{ needs.eslint.outputs.result }}
+            ${{ needs.translation-check.outputs.result }}
+
+            ${{ needs.translation-check.outputs.details }}
 
             Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
             })
@@ -192,7 +234,7 @@ jobs:
   comment-failure:
     name: Leave a comment on failure
     if: ${{ failure() }}
-    needs: [build, deploy, commitlint, eslint]
+    needs: [build, deploy, commitlint, eslint, translation-check]
     runs-on: ubuntu-latest
     steps:
       - name: Leave a comment
@@ -215,6 +257,9 @@ jobs:
             ${{ needs.deploy.outputs.result }}
             ${{ needs.commitlint.outputs.result }}
             ${{ needs.eslint.outputs.result }}
+            ${{ needs.translation-check.outputs.result }}
+
+            ${{ needs.translation-check.outputs.details }}
 
             Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
             })
